name: CI Pipe
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: dinelefox
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install tox
      - run: |
          echo "DB_USER=postgres" >> .env
          echo "DB_PASSWORD=dinelefox" >> .env
          echo "DB_HOST=localhost" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_NAME=all_solvit" >> .env
          echo "HIDE_DEV_FILES=true" >> .env
          echo "UVICORN_HOST=0.0.0.0" >> .env
          echo "UVICORN_PORT=8000" >> .env
      - run: tox
